### ISSUE TITLE
Fetch example?

### ISSUE THREAD

**Issue by cem2ran** [reazen/relude-fetch#11]
I've been trying to use this library, but hit a wall when trying to work with the response. I'm not sure if this is an error on my side (understanding) or issue with the library as I'm getting the following error with the demo example too:
```reason
open Relude;

// Defines our API error type
module Error = {
  type t = ReludeFetch.Error.t(string);
  let show = error => ReludeFetch.Error.show(a => a, error);
  module Type = {
    type nonrec t = t;
  };
};

// Open the IO infix operators
module IOE = IO.WithError(Error.Type);
open IOE.Infix;

let textResponse = ReludeFetch.fetch("some_url") >>= ReludeFetch.Response.text;
```

Last line errors with:
```
Error: This expression has type
         Fetch.Response.t => Relude.IO.t(string, ReludeFetch_Error.t('a))
       but an expression was expected of type
         Fetch.response => IOE.Monad.t('b)
       Type Fetch.Response.t is not compatible with type Fetch.response
```

**Comment by andywhite37** [comment]
Sometimes these types of errors are a result of not including all the dependencies in the bsconfig. Most of the deps are listed as `peerDependencies` to avoid the multiple library version issues. Do you have bastet, relude, and relude-fetch as dependencies?

**Comment by cem2ran** [comment]
I do have all peerDependencies installed. Here are my bs-dependencies:
```
"bs-dependencies": [
    "reason-react",
    "decco",
    "bs-bastet",
    "relude",
    "relude-fetch"
  ],
```

**Comment by andywhite37** [comment]
Ah, I think relude-fetch is a bit behind on dependencies, let me get everything up-to-date.

**Comment by mlms13** [comment]
I think you may need `bs-fetch` in your bsconfig dependencies in order for bsb to know that `Fetch.Response.t` and `Fetch.response` are actually the same type. We should probably add clear installation instructions to the README.

**Comment by andywhite37** [comment]
Yeah, I think that's likely the problem.

**Comment by cem2ran** [comment]
🤦‍♂️ Right, that makes completely explains the error. Thanks!

**Comment by andywhite37** [comment]
I pushed a dependency update in v0.8.0, but that shouldn't matter. I also added a short note in the README about dependencies to hopefully prevent this for future users.
