### ISSUE TITLE
Type mismatch between the output of fetch post and ensure2xx

### ISSUE THREAD

**Issue by broerjuang** [reazen/relude-fetch#8]
Hi guys, thanks for the awesome libraries! 

I tried to do this using ReludeFetch but the code couldn't comple since the output of `ReludeFetch.post` is not compatible with the input of `ReludeFetch.Response.StatusCode.ensure2xx`.

```reason
module IO = Relude.IO;
module Error = ReludeFetch.Error;

module IOE = IO.WithError({
  type t = Error.t(Decco.decodeError)
})

[@decco encode]
type request = {
  username: string,
  password: string,
};

[@decco decode]
  type response = {
  token: string,
};

let login = (~username, ~password) => {
    ReludeFetch.post(
      ~headers=Headers.acceptJson,
      ~body=
        ReludeFetch.Body.Content.Json(
          request_encode({
            username,
            password,
          }),
        ),
       "/some/login",
    )
    >>= ReludeFetch.Response.StatusCode.ensure2xx;
  };
};
```

When I look at the [this](https://github.com/reazen/relude-fetch/blob/master/src/ReludeFetch.re#L40) it has `Relude.IO.t(Fetch.response, Error.t('decodeError))` but  it should be `Fetch.Response.t`.  Am I compose the wrong function here?

**Comment by mlms13** [comment]
Hi @broerjuang, what do the `dependencies` look like in your `bsconfig.json`? `Fetch.Response.t` is just an alias for `Fetch.response` in the underlying `bs-fetch` library, but if you don't have `bs-fetch` explicitly listed as a dependency, I don't think the compiler is able to figure that out.

Assuming that's the problem, I'll update the README with better installation instructions.

**Comment by broerjuang** [comment]
I don't have bs-fetch registered in my deps 😅🙏. A silly mistake. Yes, It will be helpfull if relude-fetch including a section on what needs to be installed before using it. And thanks for the answer @mlms13 been waiting these set of tools on my reason react development.
